from typing import Union
import numpy as np

def add(x: Union[int, float], y: Union[int, float]) -> Union[int, float]: ...
def multiply_array(m: np.ndarray, value: Union[int, float]) -> np.ndarray: ...
def create_vector(size: int) -> np.ndarray: ...
def create_matrix(rows: int, columns: int) -> np.ndarray: ...
def matmul(a: np.ndarray, b: np.ndarray) -> np.ndarray: ...
def available_simd_instructions() -> str: ...
